[package]
name = "aio-asset-normalizer"
version = "0.1.0"
edition = "2021"
description = "A cross-platform GLB editor and generic BVH motion standardization tool"
license = "MIT"
authors = []

[dependencies]
three-d = { version = "0.19", features = ["egui-gui"] }
gltf = { version = "1.4", features = ["KHR_lights_punctual", "extensions", "names"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
sha2 = "0.10"
sys-locale = "0.3"
dirs = "5"
rfd = "0.15"
arboard = "3"
open = "5"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
winit = "0.28"

three-d-asset = { version = "0.10", features = ["gltf", "image"] }
egui-phosphor = "0.12"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
