version: 1
language: auto
view:
  show_grid: true
  show_axes: true
  show_origin: true
file_tree:
  show_all_files: false
  last_opened_directory: null
log_viewer:
  auto_scroll: true
converter:
  blender_path: null
  show_all_files: false
  last_opened_directory: null
