#!/usr/bin/env python3
"""Build an Inno Setup installer for AIO Asset Normalizer on Windows."""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


APP_NAME = "AIO Asset Normalizer"
APP_ID = "aio-asset-normalizer"
BINARY_NAME = "aio-asset-normalizer"
PUBLISHER = "AIO Asset Normalizer Contributors"
ICON_NAME = "aio-asset-normalizer.ico"
REGISTRY_KEY = rf"Software\{PUBLISHER}\{APP_NAME}"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CARGO_TOML = PROJECT_ROOT / "Cargo.toml"
TARGET_DIR = PROJECT_ROOT / "target"
ASSETS_DIR = PROJECT_ROOT / "assets"


def read_version() -> str:
    """Read the package version from Cargo.toml."""
    text = CARGO_TOML.read_text(encoding="utf-8")
    match = re.search(r"(?m)^\s*version\s*=\s*\"([^\"]+)\"", text)
    if match is None:
        raise ValueError(f"Could not read the package version from {CARGO_TOML}")
    return match.group(1)


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def run(command: list[object], **kwargs: object) -> subprocess.CompletedProcess[bytes]:
    print(f"  -> {' '.join(str(item) for item in command)}")
    return subprocess.run(command, check=True, **kwargs)


def find_iscc() -> Path:
    """Find the Inno Setup compiler in PATH or common installation folders."""
    iscc = shutil.which("iscc")
    if iscc:
        return Path(iscc)

    candidates = [
        Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"),
        Path(r"C:\Program Files\Inno Setup 6\ISCC.exe"),
        Path(r"C:\Program Files (x86)\Inno Setup 5\ISCC.exe"),
    ]
    local_app_data = os.environ.get("LOCALAPPDATA")
    if local_app_data:
        candidates.append(
            Path(local_app_data) / "Programs" / "Inno Setup 6" / "ISCC.exe"
        )

    for candidate in candidates:
        if candidate.exists():
            return candidate

    print("[ERROR] Inno Setup was not found (iscc.exe).")
    print("        Install Inno Setup 6 from https://jrsoftware.org/isinfo.php")
    raise SystemExit(1)


def inno_path(path: Path) -> str:
    """Return a Windows path escaped for an Inno Setup string literal."""
    return str(path).replace("/", "\\").replace('"', '""')


def generate_iss(package_dir: Path, version: str, output_dir: Path) -> Path:
    """Generate the temporary Inno Setup project used for the installer."""
    executable_path = inno_path(package_dir / f"{BINARY_NAME}.exe")
    icon_path = inno_path(package_dir / "assets" / ICON_NAME)
    output_path = inno_path(output_dir)
    registry_key = REGISTRY_KEY.replace('"', '""')

    lines = [
        "; Inno Setup script for AIO Asset Normalizer",
        "; Auto-generated by build-windows.py",
        "",
        "[Setup]",
        "AppId={{D0E5C0A7-3D2E-4B5A-9D75-5E799C3E8F4B}}",
        f"AppName={APP_NAME}",
        f"AppVersion={version}",
        f"AppPublisher={PUBLISHER}",
        f"DefaultDirName={{autopf}}\\{APP_NAME}",
        f"DefaultGroupName={APP_NAME}",
        f"OutputDir={output_path}",
        f"OutputBaseFilename={APP_ID}-{version}-win-x64-setup",
        "Compression=lzma2/ultra64",
        "SolidCompression=yes",
        "WizardStyle=modern",
        "ArchitecturesInstallIn64BitMode=x64compatible",
        "PrivilegesRequiredOverridesAllowed=dialog",
        f"UninstallDisplayName={APP_NAME}",
        f"UninstallDisplayIcon={{app}}\\{BINARY_NAME}.exe",
        f"SetupIconFile={icon_path}",
        "",
        "[Languages]",
        'Name: "english"; MessagesFile: "compiler:Default.isl"',
        "",
        "[Tasks]",
        'Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional options:"',
        "",
        "[Files]",
        f'Source: "{executable_path}"; DestDir: "{{app}}"; Flags: ignoreversion',
        "",
        "[Icons]",
        f'Name: "{{group}}\\{APP_NAME}"; Filename: "{{app}}\\{BINARY_NAME}.exe"',
        'Name: "{group}\\Uninstall AIO Asset Normalizer"; Filename: "{uninstallexe}"',
        f'Name: "{{autodesktop}}\\{APP_NAME}"; Filename: "{{app}}\\{BINARY_NAME}.exe"; Tasks: desktopicon',
        "",
        "[Registry]",
        f'Root: HKCU; Subkey: "{registry_key}"; ValueType: string; ValueName: "InstallPath"; ValueData: "{{app}}"; Flags: uninsdeletekey',
        f'Root: HKCU; Subkey: "{registry_key}"; ValueType: string; ValueName: "Version"; ValueData: "{version}"; Flags: uninsdeletekey',
        "",
        "[Run]",
        f'Filename: "{{app}}\\{BINARY_NAME}.exe"; Description: "Launch {APP_NAME}"; Flags: nowait postinstall skipifsilent',
        "",
    ]
    iss_path = package_dir / f"{APP_ID}.iss"
    iss_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  [OK] Generated Inno Setup script: {iss_path}")
    return iss_path


def build_installer(
    version: str, output_dir: Path, release: bool, skip_build: bool
) -> Path:
    profile = "release" if release else "debug"
    profile_dir = TARGET_DIR / profile

    print("\n" + "=" * 60)
    print(f"  {APP_NAME} Windows installer")
    print(f"  Version: {version}  Profile: {profile}")
    print("=" * 60 + "\n")

    if not skip_build:
        print("[1/4] Building executable...")
        command = ["cargo", "build"]
        if release:
            command.append("--release")
        run(command, cwd=PROJECT_ROOT)
    else:
        print("[1/4] Skipping build (--skip-build).")

    print("[2/4] Preparing installer files...")
    executable_name = f"{BINARY_NAME}.exe"
    executable_source = profile_dir / executable_name
    icon_source = ASSETS_DIR / "icon" / ICON_NAME
    if not executable_source.exists():
        print(f"[ERROR] Executable not found: {executable_source}")
        raise SystemExit(1)
    if not icon_source.exists():
        print(f"[ERROR] Installer icon not found: {icon_source}")
        raise SystemExit(1)
    print(
        f"  [OK] {executable_source} "
        f"({executable_source.stat().st_size / 1024 / 1024:.1f} MB)"
    )

    ensure_dir(output_dir)
    with tempfile.TemporaryDirectory(prefix="aio-asset-normalizer-inno-") as temporary_directory:
        package_dir = Path(temporary_directory) / "package"
        ensure_dir(package_dir / "assets")
        shutil.copy2(executable_source, package_dir / executable_name)
        shutil.copy2(icon_source, package_dir / "assets" / ICON_NAME)

        print("[3/4] Generating Inno Setup project...")
        iss_path = generate_iss(package_dir, version, output_dir)

        print("[4/4] Compiling installer...")
        iscc = find_iscc()
        print(f"  [OK] Inno Setup: {iscc}")
        run([iscc, iss_path])

    installer_path = output_dir / f"{APP_ID}-{version}-win-x64-setup.exe"
    if not installer_path.exists():
        print(
            "[ERROR] Inno Setup finished, but the installer was not found "
            f"in {output_dir}"
        )
        raise SystemExit(1)

    print("\n" + "=" * 60)
    print(f"  [OK] Installer: {installer_path}")
    print(f"  [OK] Size: {installer_path.stat().st_size / 1024 / 1024:.1f} MB")
    print("=" * 60 + "\n")
    return installer_path


def main() -> int:
    parser = argparse.ArgumentParser(
        description=f"Build the {APP_NAME} Windows installer"
    )
    parser.add_argument(
        "--version", "-v", default=None, help="Version (default: read from Cargo.toml)"
    )
    parser.add_argument(
        "--output",
        "-o",
        default="packaging/out",
        help="Output directory (default: packaging/out)",
    )
    parser.add_argument("--debug", action="store_true", help="Use the debug executable")
    parser.add_argument(
        "--skip-build", action="store_true", help="Package an existing executable"
    )
    args = parser.parse_args()

    version = args.version or read_version()
    output_dir = Path(args.output).resolve()
    build_installer(
        version, output_dir, release=not args.debug, skip_build=args.skip_build
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
